/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan2;

/**
 *
 * @author Zafira
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Absen = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jRadioButtonTKJ = new javax.swing.JRadioButton();
        jRadioButtonRPL = new javax.swing.JRadioButton();
        jCheckBoxDes = new javax.swing.JCheckBox();
        jCheckBoxPro = new javax.swing.JCheckBox();
        jCheckBoxDev = new javax.swing.JCheckBox();
        jCheckBoxTek = new javax.swing.JCheckBox();
        jButtonKeluar = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Biodata Siswa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 110, 30);

        jLabel2.setText("Hobi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 170, 50, 14);

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 50, 50, 14);

        jLabel4.setText("Absen");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 90, 40, 14);

        jLabel5.setText("Jurusan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 130, 60, 14);
        jPanel1.add(Absen);
        Absen.setBounds(110, 90, 170, 30);
        jPanel1.add(Nama);
        Nama.setBounds(110, 50, 170, 30);

        jRadioButtonTKJ.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup.add(jRadioButtonTKJ);
        jRadioButtonTKJ.setText("TKJ");
        jPanel1.add(jRadioButtonTKJ);
        jRadioButtonTKJ.setBounds(190, 130, 50, 23);

        jRadioButtonRPL.setBackground(new java.awt.Color(153, 255, 153));
        buttonGroup.add(jRadioButtonRPL);
        jRadioButtonRPL.setText("RPL");
        jRadioButtonRPL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRPLActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonRPL);
        jRadioButtonRPL.setBounds(110, 130, 50, 23);

        jCheckBoxDes.setBackground(new java.awt.Color(153, 255, 153));
        jCheckBoxDes.setText("Designer");
        jPanel1.add(jCheckBoxDes);
        jCheckBoxDes.setBounds(110, 200, 110, 23);

        jCheckBoxPro.setBackground(new java.awt.Color(153, 255, 153));
        jCheckBoxPro.setText("Programmer");
        jPanel1.add(jCheckBoxPro);
        jCheckBoxPro.setBounds(110, 170, 100, 23);

        jCheckBoxDev.setBackground(new java.awt.Color(153, 255, 153));
        jCheckBoxDev.setText("Developer");
        jPanel1.add(jCheckBoxDev);
        jCheckBoxDev.setBounds(230, 200, 120, 23);

        jCheckBoxTek.setBackground(new java.awt.Color(153, 255, 153));
        jCheckBoxTek.setText("Teknisi");
        jPanel1.add(jCheckBoxTek);
        jCheckBoxTek.setBounds(230, 170, 110, 23);

        jButtonKeluar.setText("Keluar");
        jButtonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonKeluar);
        jButtonKeluar.setBounds(270, 250, 80, 23);

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubmit);
        jButtonSubmit.setBounds(60, 250, 80, 23);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHapus);
        jButtonHapus.setBounds(160, 250, 90, 23);

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 290, 290, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonRPLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRPLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonRPLActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        String nama = Nama.getText();
        int absen = Integer.parseInt(Absen.getText());
        String jurusan;
        String hobi = "";
        
        if (jRadioButtonRPL.isSelected())
            jurusan = "RPL";
        else if (jRadioButtonTKJ.isSelected())
            jurusan = "TKJ";
        else
            jurusan = "";
        
        if(jCheckBoxPro.isSelected())
            hobi += jCheckBoxPro.getText()+" ";
        if (jCheckBoxDes.isSelected())
            hobi += jCheckBoxDes.getText()+" "; 
        if (jCheckBoxTek.isSelected())
            hobi += jCheckBoxTek.getText()+" ";
        if (jCheckBoxDev.isSelected())
            hobi += jCheckBoxDev.getText()+" ";
        
        jTextArea.setText("Nama : "+nama+"\nAbsen : "+absen+"\nJurusan : "+jurusan+"\nHobi : "+hobi);
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
        jTextArea.setText("");
        Nama.setText("");
        Absen.setText("");
        jCheckBoxPro.setSelected(false);
        jCheckBoxDes.setSelected(false);
        jCheckBoxTek.setSelected(false);
        jCheckBoxDev.setSelected(false);
        buttonGroup.clearSelection();
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Nama;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonKeluar;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JCheckBox jCheckBoxDes;
    private javax.swing.JCheckBox jCheckBoxDev;
    private javax.swing.JCheckBox jCheckBoxPro;
    private javax.swing.JCheckBox jCheckBoxTek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonRPL;
    private javax.swing.JRadioButton jRadioButtonTKJ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
